spring:
  datasource:
    url               : jdbc:postgresql://localhost:5432/db_payment
    username          : postgres
    password          : qwerty
    driver-class-name : org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
server:
  port: 8080
